version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - /data/kafka/data:/data
    ports:
      - "2181:2181"
       
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.9.191
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      # KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /data/kafka/kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
        #- /opt/kafka:/opt/kafka
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181
