FROM ubuntu:16.04
MAINTAINER mairoot

RUN sed -i "1ideb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main" /etc/apt/sources.list
RUN apt-get update && apt-get upgrade -y --allow-unauthenticated
RUN apt-get install -y --allow-unauthenticated \
        php5.6 \
        php5.6-bz2 \
        php5.6-cgi \
        php5.6-cli \
        php5.6-common \
        php5.6-curl \
        php5.6-dev \
        php5.6-enchant \
        php5.6-fpm \
        php5.6-gd \
        php5.6-gmp \
        php5.6-imap \
        php5.6-interbase \
        php5.6-intl \
        php5.6-json \
        php5.6-ldap \
        php5.6-mbstring \
        php5.6-mcrypt \
        php5.6-mysql \
        php5.6-odbc \
        php5.6-opcache \
        php5.6-pgsql \
        php5.6-phpdbg \
        php5.6-pspell \
        php5.6-readline \
        php5.6-recode \
        php5.6-snmp \
        php5.6-sqlite3 \
        php5.6-sybase \
        php5.6-tidy \
        php5.6-xmlrpc \
        php5.6-xsl \
        php5.6-zip
RUN apt-get install -y --allow-unauthenticated zip unzip apache2 libapache2-mod-php5.6 mariadb-common mariadb-server mariadb-client curl vim net-tools sysstat

ENV LOG_STDOUT **Boolean**
ENV LOG_STDERR **Boolean**
ENV LOG_LEVEL warn
ENV ALLOW_OVERRIDE All
ENV DATE_TIMEZONE CST
ENV TERM dumb

COPY run-lamp.sh /usr/sbin/
COPY wp.conf /etc/apache2/sites-enabled/

RUN chmod +x /usr/sbin/run-lamp.sh
RUN chown -R www-data:www-data /var/www/html

VOLUME /var/www/html
VOLUME /var/log/httpd
VOLUME /var/lib/mysql
VOLUME /var/log/mysql
VOLUME /etc/apache2

EXPOSE 80 3306

CMD ["sh", "-c","/usr/sbin/run-lamp.sh"]